on:
  push:
    tags:
      - dev.*
    branches:
      - dev
name: ssh
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEV_KNOWN_HOSTS }}
      - name: checkout
        uses: actions/checkout@v3
      - name: rsync over ssh
        run: rsync -ar --delete *  ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:~/backend_temp
      - name: docker-compose build
        run: ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "cd frontend/ && COMPOSE_FILE=docker-compose-dev.yml docker compose build"
      - name: docker-compose up
        run: ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "cd frontend/ && COMPOSE_FILE=docker-compose-dev.yml docker compose up -d"

